import { DashboardData, OversharedLicense } from '@/hooks/useDashboardData';

// Mock data for development
export const mockDashboardData: DashboardData = {
  totalPublications: 2866,
  totalUsers: 428,
  totalLicenses: 89234,
  licensesLast12Months: 6824,
  licensesLastMonth: 573,
  licensesLastWeek: 127,
  licensesLastDay: 18,
  oldestLicenseDate: "2022-01-15",
  latestLicenseDate: "2025-10-02",
  oversharedLicensesCount: 23,
  publicationTypes: [
    { name: "EPUB", count: 1284 },
    { name: "PDF", count: 892 },
    { name: "Audiobooks", count: 456 },
    { name: "Comics", count: 234 },
  ],
  licenseStatuses: [
    { name: "Ready", count: 45632 },
    { name: "Active", count: 28456 },
    { name: "Expired", count: 12834 },
    { name: "Revoked", count: 1856 },
    { name: "Canceled", count: 456 },
  ],
  chartData: [
    { month: "Jan", licenses: 245 },
    { month: "Feb", licenses: 312 },
    { month: "Mar", licenses: 198 },
    { month: "Apr", licenses: 427 },
    { month: "May", licenses: 389 },
    { month: "Jun", licenses: 516 },
    { month: "Jul", licenses: 634 },
    { month: "Aug", licenses: 573 },
    { month: "Sep", licenses: 692 },
    { month: "Oct", licenses: 758 },
    { month: "Nov", licenses: 841 },
    { month: "Dec", licenses: 923 },
  ],
};

export const mockOversharedLicenses: OversharedLicense[] = [
  {
    id: "lic-001",
    title: "The Complete Guide to Modern Web Development with React and TypeScript",
    user: "john.doe@example.com",
    type: "loan",
    status: "active",
    devices: 5,
  },
  {
    id: "lic-002",
    title: "Advanced JavaScript Patterns",
    user: "jane.smith@example.com",
    type: "buy",
    status: "ready",
    devices: 4,
  },
  {
    id: "lic-003",
    title: "Mastering Node.js: Build Scalable Applications",
    user: "bob.wilson@example.com",
    type: "loan",
    status: "active",
    devices: 6,
  },
  {
    id: "lic-004",
    title: "CSS Grid and Flexbox: A Complete Guide",
    user: "alice.brown@example.com",
    type: "buy",
    status: "expired",
    devices: 3,
  },
  {
    id: "lic-005",
    title: "Python for Data Science and Machine Learning",
    user: "charlie.davis@example.com",
    type: "loan",
    status: "active",
    devices: 7,
  },
];