import { DashboardData, OversharedLicense } from '@/hooks/useDashboardData';

// Mock data for development
export const mockDashboardData: DashboardData = {
  total_publications: 2866,
  total_users: 428,
  total_licenses: 89234,
  licenses_last_12_months: 6824,
  licenses_last_month: 573,
  licenses_last_week: 127,
  licenses_last_day: 18,
  oldest_license_date: "2022-01-15",
  latest_license_date: "2025-10-02",
  overshared_licenses_count: 23,
  publication_types: [
    { name: "EPUB", count: 1284 },
    { name: "PDF", count: 892 },
    { name: "Audiobooks", count: 456 },
    { name: "Comics", count: 234 },
  ],
  license_statuses: [
    { name: "Ready", count: 45632 },
    { name: "Active", count: 28456 },
    { name: "Expired", count: 12834 },
    { name: "Revoked", count: 1856 },
    { name: "Canceled", count: 456 },
  ],
  chart_data: [
    { month: "Jan", licenses: 245 },
    { month: "Feb", licenses: 312 },
    { month: "Mar", licenses: 198 },
    { month: "Apr", licenses: 427 },
    { month: "May", licenses: 389 },
    { month: "Jun", licenses: 516 },
    { month: "Jul", licenses: 634 },
    { month: "Aug", licenses: 573 },
    { month: "Sep", licenses: 692 },
    { month: "Oct", licenses: 758 },
    { month: "Nov", licenses: 841 },
    { month: "Dec", licenses: 923 },
  ],
};

export const mockOversharedLicenses: OversharedLicense[] = [
  {
    id: "lic-001",
    publication_id: "pub-123",
    alt_id: "alt-123",
    title: "The Complete Guide to Modern Web Development with React and TypeScript",
    user_id: "user-001",
    user_email: "john.doe@example.com",
    type: "loan",
    status: "active",
    devices: 5,
  },
  {
    id: "lic-002",
    publication_id: "pub-456",
    alt_id: "alt-456",
    title: "Advanced JavaScript Patterns",
    user_id: "user-002",
    user_email: "jane.smith@example.com",
    type: "buy",
    status: "ready",
    devices: 4,
  },
  {
    id: "lic-003",
    publication_id: "pub-789",
    alt_id: "alt-789",
    title: "Mastering Node.js: Build Scalable Applications",
    user_id: "user-003",
    user_email: "bob.wilson@example.com",
    type: "loan",
    status: "active",
    devices: 6,
  },
  {
    id: "lic-004",
    publication_id: "pub-101",
    alt_id: "alt-101",
    title: "CSS Grid and Flexbox: A Complete Guide",
    user_id: "user-004",
    user_email: "alice.brown@example.com",
    type: "buy",
    status: "expired",
    devices: 3,
  },
  {
    id: "lic-005",
    publication_id: "pub-212",
    alt_id: "alt-212",
    title: "Python for Data Science and Machine Learning",
    user_id: "user-005",
    user_email: "charlie.davis@example.com",
    type: "loan",
    status: "active",
    devices: 7,
  },
];