// Copyright 2025 EDRLab
// Licensed under the BSD 3-Clause License (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License in the root directory of this source
// distribution or at https://opensource.org/license/bsd-3-clause/

package main

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
)

type Publication struct {
	CreatedAt     time.Time `json:"created_at"`
	Provider      string    `json:"provider,omitempty"`
	UUID          string    `json:"uuid"`
	AltID         string    `json:"alt_id,omitempty"`
	ContentType   string    `json:"content_type"`
	Title         string    `json:"title"`
	Description   string    `json:"description,omitempty"`
	Authors       string    `json:"authors,omitempty"`
	Publishers    string    `json:"publishers,omitempty"`
	CoverUrl      string    `json:"cover_url,omitempty"`
	EncryptionKey []byte    `json:"encryption_key"`
	Href          string    `json:"href"`
	Size          uint32    `json:"size"`
	Checksum      string    `json:"checksum"`
}

func Publications(w http.ResponseWriter, r *http.Request) {

	page := r.Context().Value(PageKey).(int)
	perPage := r.Context().Value(PerPageKey).(int)
	publications := []Publication{
		{
			CreatedAt:   time.Now().AddDate(0, 0, -10),
			Provider:    "Provider A",
			UUID:        "123e4567-e89b-12d3-a456-426614174000",
			AltID:       "ALTID001",
			ContentType: "application/epub+zip",
			Title:       "The Great Gatsby",
			Description: "A classic American novel set in the Jazz Age.",
			Authors:     "F. Scott Fitzgerald",
			Publishers:  "Scribner",
			CoverUrl:    "https://covers.openlibrary.org/b/id/7222246-L.jpg",
			EncryptionKey: []byte{0x01, 0x02, 0x03, 0x04},
			Href:        "http://example.com/publication1.epub",
			Size:        204800,
			Checksum:    "abc123checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -5),
			Provider:    "Provider B",
			UUID:        "223e4567-e89b-12d3-a456-426614174001",
			AltID:       "ALTID002",
			ContentType: "application/pdf+lcp",
			Title:       "To Kill a Mockingbird",
			Description: "A gripping tale of racial injustice and childhood innocence.",
			Authors:     "Harper Lee",
			Publishers:  "J.B. Lippincott & Co.",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8228691-L.jpg",
			EncryptionKey: []byte{0x05, 0x06, 0x07, 0x08},
			Href:        "http://example.com/publication2.pdf",
			Size:        409600,
			Checksum:    "def456checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -15),
			Provider:    "Provider C",
			UUID:        "323e4567-e89b-12d3-a456-426614174002",
			ContentType: "application/epub+zip",
			Title:       "1984",
			Description: "A dystopian social science fiction novel and cautionary tale.",
			Authors:     "George Orwell",
			Publishers:  "Secker & Warburg",
			CoverUrl:    "https://covers.openlibrary.org/b/id/7222246-L.jpg",
			EncryptionKey: []byte{0x09, 0x0A, 0x0B, 0x0C},
			Href:        "http://example.com/publication3.epub",
			Size:        312000,
			Checksum:    "ghi789checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -20),
			Provider:    "Provider A",
			UUID:        "423e4567-e89b-12d3-a456-426614174003",
			AltID:       "ALTID004",
			ContentType: "application/epub+zip",
			Title:       "Pride and Prejudice",
			Description: "A romantic novel of manners.",
			Authors:     "Jane Austen",
			Publishers:  "T. Egerton",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8235174-L.jpg",
			EncryptionKey: []byte{0x0D, 0x0E, 0x0F, 0x10},
			Href:        "http://example.com/publication4.epub",
			Size:        275000,
			Checksum:    "jkl012checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -25),
			Provider:    "Provider D",
			UUID:        "523e4567-e89b-12d3-a456-426614174004",
			ContentType: "application/pdf+lcp",
			Title:       "The Catcher in the Rye",
			Description: "A story about teenage rebellion and alienation.",
			Authors:     "J.D. Salinger",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8228691-L.jpg",
			EncryptionKey: []byte{0x11, 0x12, 0x13, 0x14},
			Href:        "http://example.com/publication5.pdf",
			Size:        198000,
			Checksum:    "mno345checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -30),
			Provider:    "Provider B",
			UUID:        "623e4567-e89b-12d3-a456-426614174005",
			AltID:       "ALTID006",
			ContentType: "application/epub+zip",
			Title:       "Harry Potter and the Philosopher's Stone",
			Description: "A young wizard discovers his magical heritage.",
			Authors:     "J.K. Rowling",
			Publishers:  "Bloomsbury",
			CoverUrl:    "https://covers.openlibrary.org/b/id/10521270-L.jpg",
			EncryptionKey: []byte{0x15, 0x16, 0x17, 0x18},
			Href:        "http://example.com/publication6.epub",
			Size:        432000,
			Checksum:    "pqr678checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -35),
			Provider:    "Provider E",
			UUID:        "723e4567-e89b-12d3-a456-426614174006",
			ContentType: "application/epub+zip",
			Title:       "The Hobbit",
			Description: "A fantasy novel about the adventures of Bilbo Baggins.",
			Authors:     "J.R.R. Tolkien",
			Publishers:  "Allen & Unwin",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8486264-L.jpg",
			EncryptionKey: []byte{0x19, 0x1A, 0x1B, 0x1C},
			Href:        "http://example.com/publication7.epub",
			Size:        385000,
			Checksum:    "stu901checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -40),
			Provider:    "Provider A",
			UUID:        "823e4567-e89b-12d3-a456-426614174007",
			AltID:       "ALTID008",
			ContentType: "application/pdf+lcp",
			Title:       "Brave New World",
			Description: "A dystopian novel set in a futuristic World State.",
			Authors:     "Aldous Huxley",
			Publishers:  "Chatto & Windus",
			EncryptionKey: []byte{0x1D, 0x1E, 0x1F, 0x20},
			Href:        "http://example.com/publication8.pdf",
			Size:        294000,
			Checksum:    "vwx234checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -45),
			Provider:    "Provider F",
			UUID:        "923e4567-e89b-12d3-a456-426614174008",
			ContentType: "application/epub+zip",
			Title:       "The Lord of the Rings",
			Description: "An epic high-fantasy novel.",
			Authors:     "J.R.R. Tolkien",
			Publishers:  "Allen & Unwin",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8478508-L.jpg",
			EncryptionKey: []byte{0x21, 0x22, 0x23, 0x24},
			Href:        "http://example.com/publication9.epub",
			Size:        1248000,
			Checksum:    "yza567checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -50),
			Provider:    "Provider C",
			UUID:        "a23e4567-e89b-12d3-a456-426614174009",
			AltID:       "ALTID010",
			ContentType: "application/epub+zip",
			Title:       "Animal Farm",
			Description: "An allegorical novella about revolution and betrayal.",
			Authors:     "George Orwell",
			Publishers:  "Secker & Warburg",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x25, 0x26, 0x27, 0x28},
			Href:        "http://example.com/publication10.epub",
			Size:        112000,
			Checksum:    "bcd890checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -55),
			Provider:    "Provider G",
			UUID:        "b23e4567-e89b-12d3-a456-42661417400a",
			ContentType: "application/pdf+lcp",
			Title:       "Moby-Dick",
			Description: "The saga of Captain Ahab's obsessive quest.",
			Authors:     "Herman Melville",
			Publishers:  "Harper & Brothers",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x29, 0x2A, 0x2B, 0x2C},
			Href:        "http://example.com/publication11.pdf",
			Size:        687000,
			Checksum:    "efg123checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -60),
			Provider:    "Provider D",
			UUID:        "c23e4567-e89b-12d3-a456-42661417400b",
			AltID:       "ALTID012",
			ContentType: "application/epub+zip",
			Title:       "War and Peace",
			Description: "A historical novel about the French invasion of Russia.",
			Authors:     "Leo Tolstoy",
			Publishers:  "The Russian Messenger",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x2D, 0x2E, 0x2F, 0x30},
			Href:        "http://example.com/publication12.epub",
			Size:        1456000,
			Checksum:    "hij456checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -65),
			Provider:    "Provider H",
			UUID:        "d23e4567-e89b-12d3-a456-42661417400c",
			ContentType: "application/epub+zip",
			Title:       "Jane Eyre",
			Description: "A Bildungsroman following the emotions and experiences of its heroine.",
			Authors:     "Charlotte Brontë",
			Publishers:  "Smith, Elder & Co.",
			EncryptionKey: []byte{0x31, 0x32, 0x33, 0x34},
			Href:        "http://example.com/publication13.epub",
			Size:        523000,
			Checksum:    "klm789checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -70),
			Provider:    "Provider E",
			UUID:        "e23e4567-e89b-12d3-a456-42661417400d",
			AltID:       "ALTID014",
			ContentType: "application/pdf+lcp",
			Title:       "Wuthering Heights",
			Description: "A tale of passion and revenge on the Yorkshire moors.",
			Authors:     "Emily Brontë",
			Publishers:  "Thomas Cautley Newby",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x35, 0x36, 0x37, 0x38},
			Href:        "http://example.com/publication14.pdf",
			Size:        398000,
			Checksum:    "nop012checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -75),
			Provider:    "Provider I",
			UUID:        "f23e4567-e89b-12d3-a456-42661417400e",
			ContentType: "application/epub+zip",
			Title:       "The Odyssey",
			Description: "An ancient Greek epic poem about Odysseus's journey home.",
			Authors:     "Homer",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x39, 0x3A, 0x3B, 0x3C},
			Href:        "http://example.com/publication15.epub",
			Size:        456000,
			Checksum:    "qrs345checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -80),
			Provider:    "Provider J",
			UUID:        "023e4567-e89b-12d3-a456-42661417400f",
			AltID:       "ALTID016",
			ContentType: "application/epub+zip",
			Title:       "Crime and Punishment",
			Description: "A psychological drama about a former student who murders a pawnbroker.",
			Authors:     "Fyodor Dostoevsky",
			Publishers:  "The Russian Messenger",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x3D, 0x3E, 0x3F, 0x40},
			Href:        "http://example.com/publication16.epub",
			Size:        689000,
			Checksum:    "tuv678checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -85),
			Provider:    "Provider K",
			UUID:        "123e4567-e89b-12d3-a456-426614174010",
			ContentType: "application/pdf+lcp",
			Title:       "The Divine Comedy",
			Description: "An epic poem describing Dante's journey through Hell, Purgatory, and Paradise.",
			Authors:     "Dante Alighieri",
			EncryptionKey: []byte{0x41, 0x42, 0x43, 0x44},
			Href:        "http://example.com/publication17.pdf",
			Size:        734000,
			Checksum:    "wxy901checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -90),
			Provider:    "Provider L",
			UUID:        "223e4567-e89b-12d3-a456-426614174011",
			AltID:       "ALTID018",
			ContentType: "application/epub+zip",
			Title:       "One Hundred Years of Solitude",
			Description: "A multi-generational story of the Buendía family.",
			Authors:     "Gabriel García Márquez",
			Publishers:  "Harper & Row",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x45, 0x46, 0x47, 0x48},
			Href:        "http://example.com/publication18.epub",
			Size:        489000,
			Checksum:    "zab234checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -95),
			Provider:    "Provider M",
			UUID:        "323e4567-e89b-12d3-a456-426614174012",
			ContentType: "application/epub+zip",
			Title:       "The Brothers Karamazov",
			Description: "A philosophical novel that explores faith, doubt, and morality.",
			Authors:     "Fyodor Dostoevsky",
			Publishers:  "The Russian Messenger",
			EncryptionKey: []byte{0x49, 0x4A, 0x4B, 0x4C},
			Href:        "http://example.com/publication19.epub",
			Size:        912000,
			Checksum:    "cde567checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -100),
			Provider:    "Provider N",
			UUID:        "423e4567-e89b-12d3-a456-426614174013",
			AltID:       "ALTID020",
			ContentType: "application/pdf+lcp",
			Title:       "Don Quixote",
			Description: "The adventures of a Spanish nobleman who reads so many chivalric romances.",
			Authors:     "Miguel de Cervantes",
			Publishers:  "Francisco de Robles",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x4D, 0x4E, 0x4F, 0x50},
			Href:        "http://example.com/publication20.pdf",
			Size:        1123000,
			Checksum:    "fgh890checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -105),
			Provider:    "Provider O",
			UUID:        "523e4567-e89b-12d3-a456-426614174014",
			ContentType: "application/epub+zip",
			Title:       "Ulysses",
			Description: "A modernist novel paralleling Homer's Odyssey.",
			Authors:     "James Joyce",
			Publishers:  "Sylvia Beach",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x51, 0x52, 0x53, 0x54},
			Href:        "http://example.com/publication21.epub",
			Size:        823000,
			Checksum:    "ijk123checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -110),
			Provider:    "Provider P",
			UUID:        "623e4567-e89b-12d3-a456-426614174015",
			AltID:       "ALTID022",
			ContentType: "application/epub+zip",
			Title:       "The Iliad",
			Description: "An ancient Greek epic poem about the Trojan War.",
			Authors:     "Homer",
			EncryptionKey: []byte{0x55, 0x56, 0x57, 0x58},
			Href:        "http://example.com/publication22.epub",
			Size:        567000,
			Checksum:    "lmn456checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -115),
			Provider:    "Provider Q",
			UUID:        "723e4567-e89b-12d3-a456-426614174016",
			ContentType: "application/pdf+lcp",
			Title:       "Frankenstein",
			Description: "A Gothic novel about a scientist who creates a sapient creature.",
			Authors:     "Mary Shelley",
			Publishers:  "Lackington, Hughes, Harding, Mavor & Jones",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x59, 0x5A, 0x5B, 0x5C},
			Href:        "http://example.com/publication23.pdf",
			Size:        234000,
			Checksum:    "opq789checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -120),
			Provider:    "Provider R",
			UUID:        "823e4567-e89b-12d3-a456-426614174017",
			AltID:       "ALTID024",
			ContentType: "application/epub+zip",
			Title:       "Dracula",
			Description: "A Gothic horror novel about Count Dracula's attempt to move from Transylvania to England.",
			Authors:     "Bram Stoker",
			Publishers:  "Archibald Constable and Company",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x5D, 0x5E, 0x5F, 0x60},
			Href:        "http://example.com/publication24.epub",
			Size:        456000,
			Checksum:    "rst012checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -125),
			Provider:    "Provider S",
			UUID:        "923e4567-e89b-12d3-a456-426614174018",
			ContentType: "application/epub+zip",
			Title:       "The Picture of Dorian Gray",
			Description: "A philosophical novel about a man who remains young while his portrait ages.",
			Authors:     "Oscar Wilde",
			Publishers:  "Ward, Lock and Company",
			EncryptionKey: []byte{0x61, 0x62, 0x63, 0x64},
			Href:        "http://example.com/publication25.epub",
			Size:        289000,
			Checksum:    "uvw345checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -130),
			Provider:    "Provider T",
			UUID:        "a23e4567-e89b-12d3-a456-426614174019",
			AltID:       "ALTID026",
			ContentType: "application/pdf+lcp",
			Title:       "Alice's Adventures in Wonderland",
			Description: "A fantasy novel about a girl who falls through a rabbit hole.",
			Authors:     "Lewis Carroll",
			Publishers:  "Macmillan Publishers",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x65, 0x66, 0x67, 0x68},
			Href:        "http://example.com/publication26.pdf",
			Size:        178000,
			Checksum:    "xyz678checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -135),
			Provider:    "Provider U",
			UUID:        "b23e4567-e89b-12d3-a456-42661417401a",
			ContentType: "application/epub+zip",
			Title:       "The Adventures of Huckleberry Finn",
			Description: "A novel about a boy and a runaway slave traveling down the Mississippi River.",
			Authors:     "Mark Twain",
			Publishers:  "Chatto & Windus",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x69, 0x6A, 0x6B, 0x6C},
			Href:        "http://example.com/publication27.epub",
			Size:        367000,
			Checksum:    "abc901checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -140),
			Provider:    "Provider V",
			UUID:        "c23e4567-e89b-12d3-a456-42661417401b",
			AltID:       "ALTID028",
			ContentType: "application/epub+zip",
			Title:       "The Count of Monte Cristo",
			Description: "An adventure novel about a man wrongfully imprisoned who escapes and seeks revenge.",
			Authors:     "Alexandre Dumas",
			Publishers:  "Pétion",
			EncryptionKey: []byte{0x6D, 0x6E, 0x6F, 0x70},
			Href:        "http://example.com/publication28.epub",
			Size:        1234000,
			Checksum:    "def234checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -145),
			Provider:    "Provider W",
			UUID:        "d23e4567-e89b-12d3-a456-42661417401c",
			ContentType: "application/pdf+lcp",
			Title:       "Les Misérables",
			Description: "A French historical novel about justice, redemption, and the struggles of the poor.",
			Authors:     "Victor Hugo",
			Publishers:  "A. Lacroix, Verboeckhoven & Cie.",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x71, 0x72, 0x73, 0x74},
			Href:        "http://example.com/publication29.pdf",
			Size:        1567000,
			Checksum:    "ghi567checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -150),
			Provider:    "Provider X",
			UUID:        "e23e4567-e89b-12d3-a456-42661417401d",
			AltID:       "ALTID030",
			ContentType: "application/epub+zip",
			Title:       "The Three Musketeers",
			Description: "A historical adventure novel about a young man who joins the Musketeers.",
			Authors:     "Alexandre Dumas",
			Publishers:  "Baudry",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x75, 0x76, 0x77, 0x78},
			Href:        "http://example.com/publication30.epub",
			Size:        678000,
			Checksum:    "jkl890checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -155),
			Provider:    "Provider Y",
			UUID:        "f23e4567-e89b-12d3-a456-42661417401e",
			ContentType: "application/epub+zip",
			Title:       "The Scarlet Letter",
			Description: "A work of historical fiction about sin, guilt, and redemption in Puritan Massachusetts.",
			Authors:     "Nathaniel Hawthorne",
			Publishers:  "Ticknor, Reed & Fields",
			EncryptionKey: []byte{0x79, 0x7A, 0x7B, 0x7C},
			Href:        "http://example.com/publication31.epub",
			Size:        234000,
			Checksum:    "mno123checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -160),
			Provider:    "Provider Z",
			UUID:        "023e4567-e89b-12d3-a456-42661417401f",
			AltID:       "ALTID032",
			ContentType: "application/pdf+lcp",
			Title:       "A Tale of Two Cities",
			Description: "A historical novel set in London and Paris before and during the French Revolution.",
			Authors:     "Charles Dickens",
			Publishers:  "Chapman & Hall",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x7D, 0x7E, 0x7F, 0x80},
			Href:        "http://example.com/publication32.pdf",
			Size:        445000,
			Checksum:    "pqr456checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -165),
			Provider:    "Provider AA",
			UUID:        "123e4567-e89b-12d3-a456-426614174020",
			ContentType: "application/epub+zip",
			Title:       "Great Expectations",
			Description: "A Bildungsroman depicting the education of an orphan nicknamed Pip.",
			Authors:     "Charles Dickens",
			Publishers:  "Chapman & Hall",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x81, 0x82, 0x83, 0x84},
			Href:        "http://example.com/publication33.epub",
			Size:        512000,
			Checksum:    "stu789checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -170),
			Provider:    "Provider BB",
			UUID:        "223e4567-e89b-12d3-a456-426614174021",
			AltID:       "ALTID034",
			ContentType: "application/epub+zip",
			Title:       "Anna Karenina",
			Description: "A novel exploring themes of love, family, and Russian society.",
			Authors:     "Leo Tolstoy",
			Publishers:  "The Russian Messenger",
			EncryptionKey: []byte{0x85, 0x86, 0x87, 0x88},
			Href:        "http://example.com/publication34.epub",
			Size:        989000,
			Checksum:    "vwx012checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -175),
			Provider:    "Provider CC",
			UUID:        "323e4567-e89b-12d3-a456-426614174022",
			ContentType: "application/pdf+lcp",
			Title:       "The Metamorphosis",
			Description: "A novella about a man who wakes up one morning to find himself transformed into an insect.",
			Authors:     "Franz Kafka",
			Publishers:  "Kurt Wolff Verlag",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x89, 0x8A, 0x8B, 0x8C},
			Href:        "http://example.com/publication35.pdf",
			Size:        98000,
			Checksum:    "yza345checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -180),
			Provider:    "Provider DD",
			UUID:        "423e4567-e89b-12d3-a456-426614174023",
			AltID:       "ALTID036",
			ContentType: "application/epub+zip",
			Title:       "The Trial",
			Description: "A novel about a man arrested and prosecuted by an inaccessible authority.",
			Authors:     "Franz Kafka",
			Publishers:  "Verlag Die Schmiede",
			EncryptionKey: []byte{0x8D, 0x8E, 0x8F, 0x90},
			Href:        "http://example.com/publication36.epub",
			Size:        267000,
			Checksum:    "bcd678checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -185),
			Provider:    "Provider EE",
			UUID:        "523e4567-e89b-12d3-a456-426614174024",
			ContentType: "application/epub+zip",
			Title:       "The Grapes of Wrath",
			Description: "A novel about an Oklahoma family's migration to California during the Dust Bowl.",
			Authors:     "John Steinbeck",
			Publishers:  "The Viking Press",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x91, 0x92, 0x93, 0x94},
			Href:        "http://example.com/publication37.epub",
			Size:        567000,
			Checksum:    "efg901checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -190),
			Provider:    "Provider FF",
			UUID:        "623e4567-e89b-12d3-a456-426614174025",
			AltID:       "ALTID038",
			ContentType: "application/pdf+lcp",
			Title:       "Of Mice and Men",
			Description: "A novella about two displaced migrant ranch workers during the Great Depression.",
			Authors:     "John Steinbeck",
			Publishers:  "Covici Friede",
			EncryptionKey: []byte{0x95, 0x96, 0x97, 0x98},
			Href:        "http://example.com/publication38.pdf",
			Size:        145000,
			Checksum:    "hij234checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -195),
			Provider:    "Provider GG",
			UUID:        "723e4567-e89b-12d3-a456-426614174026",
			ContentType: "application/epub+zip",
			Title:       "Lord of the Flies",
			Description: "A novel about British boys stranded on an uninhabited island.",
			Authors:     "William Golding",
			Publishers:  "Faber and Faber",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0x99, 0x9A, 0x9B, 0x9C},
			Href:        "http://example.com/publication39.epub",
			Size:        223000,
			Checksum:    "klm567checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -200),
			Provider:    "Provider HH",
			UUID:        "823e4567-e89b-12d3-a456-426614174027",
			AltID:       "ALTID040",
			ContentType: "application/epub+zip",
			Title:       "The Sun Also Rises",
			Description: "A novel about American and British expatriates in post-World War I France and Spain.",
			Authors:     "Ernest Hemingway",
			Publishers:  "Scribner",
			EncryptionKey: []byte{0x9D, 0x9E, 0x9F, 0xA0},
			Href:        "http://example.com/publication40.epub",
			Size:        256000,
			Checksum:    "nop890checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -205),
			Provider:    "Provider II",
			UUID:        "923e4567-e89b-12d3-a456-426614174028",
			ContentType: "application/pdf+lcp",
			Title:       "For Whom the Bell Tolls",
			Description: "A novel about an American volunteer in the Spanish Civil War.",
			Authors:     "Ernest Hemingway",
			Publishers:  "Scribner",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0xA1, 0xA2, 0xA3, 0xA4},
			Href:        "http://example.com/publication41.pdf",
			Size:        498000,
			Checksum:    "qrs123checksum",
		},
		{
			CreatedAt:   time.Now().AddDate(0, 0, -210),
			Provider:    "Provider JJ",
			UUID:        "a23e4567-e89b-12d3-a456-426614174029",
			AltID:       "ALTID042",
			ContentType: "application/epub+zip",
			Title:       "The Old Man and the Sea",
			Description: "A novella about an aging Cuban fisherman's struggle with a giant marlin.",
			Authors:     "Ernest Hemingway",
			Publishers:  "Charles Scribner's Sons",
			CoverUrl:    "https://covers.openlibrary.org/b/id/8231110-L.jpg",
			EncryptionKey: []byte{0xA5, 0xA6, 0xA7, 0xA8},
			Href:        "http://example.com/publication42.epub",
			Size:        112000,
			Checksum:    "tuv456checksum",
		},
	}

	// Simple pagination logic
	start := (page - 1) * perPage
	end := start + perPage
	if start > len(publications) {
		start = len(publications)
	}
	if end > len(publications) {
		end = len(publications)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(publications[start:end])
}

var deleteCounter int

func DeletePublication(w http.ResponseWriter, r *http.Request) {
	uuid := chi.URLParam(r, "uuid")
	
	if uuid == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{
			"type":   "about:blank",
			"title":  "Invalid request",
			"detail": "UUID is required",
		})
		return
	}
	
	// Alternate between success (200) and error (400)
	deleteCounter++
	if deleteCounter%2 == 0 {
		// Return error on even calls
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{
			"type":   "about:blank",
			"title":  "Invalid request",
			"detail": "publication has been deleted",
		})
		return
	}
	
	// Return success on odd calls
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]string{
		"message": "Publication deleted successfully",
	})
}
